apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-agent-python
spec:
  selector:
    matchLabels:
      app: jenkins-agent-python # has to match .spec.template.metadata.labels
  serviceName: "jenkins-agent-python"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: jenkins-agent-python # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jenkins-agent-python
        image: jenkins-agent-python:1.0
        volumeMounts:
        - name: jenkins-agent-python-pvc
          mountPath: /var/jenkins/agent
        env:
        - name: JENKINS_URL
          value: http://jenkins:8080
        - name: JENKINS_AGENT_NAME
          value: python
        # - name: JENKINS_AGENT_NAME
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.name
        - name: JENKINS_SECRET
          value: 7d9244d9d7fb183ac1171ed275ab61987d836586011107918cff33d0a56807fb # TODO: Load from secret file using `@secret_file_path` 
        - name: JENKINS_AGENT_WORKDIR
          value: /home/jenkins/agent
        - name: TZ
          value: Europe/Zurich

  volumeClaimTemplates:
  - metadata:
      name: jenkins-agent-python-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "hostpath"  # default created by docker
      resources:
        requests:
          storage: 1Gi