apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: sql
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb # has to match .spec.template.metadata.labels
  serviceName: "mariadb"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mariadb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb:10.5.8
        ports:
        - containerPort: 3306
          name: sql
        volumeMounts:
        - name: maria-db-pvc
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: my-secret-pw12$

  volumeClaimTemplates:
  - metadata:
      name: maria-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "hostpath"  # default created by docker
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name:  mariadb-loadbalancer
spec:
  selector:
    app:  mariadb
  type:  LoadBalancer
  ports:
  - name:  sql
    port:  3306
    targetPort:  3306