apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  ports:
  - port: 1433
    name: sql
  clusterIP: None
  selector:
    app: mssql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql # has to match .spec.template.metadata.labels
  serviceName: "mssql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mssql # has to match .spec.selector.matchLabels
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/opt/bulk"]
        volumeMounts:
        - name: mssql-bulk
          mountPath: /var/opt/bulk
        securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
        ports:
        - containerPort: 1433
          name: sql
        volumeMounts:
        - name: mssql-db-pvc
          mountPath: /var/opt/mssql
        - name: mssql-bulk
          mountPath: /var/opt/bulk
        env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: MSSQL_SA_PASSWORD
            value: Password001*
          - name: TZ
            value: Europe/Zurich      
      volumes:
      - name: mssql-bulk
        persistentVolumeClaim:
          claimName: mssql-bulk-pvc

  volumeClaimTemplates:
  - metadata:
      name: mssql-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "hostpath"  # default created by docker
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name:  mssql-loadbalancer
spec:
  selector:
    app:  mssql
  type:  LoadBalancer
  ports:
  - name:  sql
    port:  1433
    targetPort:  1433