apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: sql
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres # has to match .spec.template.metadata.labels
  serviceName: "postgres"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: postgres # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:13.1  # see https://hub.docker.com/_/postgres
        ports:
        - containerPort: 3306
          name: sql
        volumeMounts:
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword-13

  volumeClaimTemplates:
  - metadata:
      name: postgres-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name:  postgres-loadbalancer
spec:
  selector:
    app:  postgres
  type:  LoadBalancer
  ports:
  - name:  sql
    port:  5432
    targetPort:  5432
