apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-bulk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/mssql-bulk"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-bulk-pvc
spec:
  storageClassName: manual
  volumeName: mssql-bulk
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 3Gi