# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mssql-bulk
# spec:
#   capacity:
#     storage: 3Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/usr/share/mssql-bulk"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-bulk-pvc
spec:
  # volumeName: mssql-bulk
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 3Gi