kind: Service
apiVersion: v1
metadata:
  name: sql1
  namespace: default
  selfLink: /api/v1/namespaces/default/services/sql1
  uid: 3a65d5bc-2739-4b20-997b-cd51530e3f8a
  resourceVersion: '4735'
  creationTimestamp: '2020-11-14T22:04:43Z'
  labels:
    io.kompose.service: sql1
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"kompose
      convert","kompose.version":"1.21.0
      (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"sql1"},"name":"sql1","namespace":"default"},"spec":{"ports":[{"name":"1433","port":1433,"targetPort":1433}],"selector":{"io.kompose.service":"sql1"}},"status":{"loadBalancer":{}}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2020-11-14T22:04:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kompose.cmd': {}
            'f:kompose.version': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:io.kompose.service': {}
        'f:spec':
          'f:ports':
            .: {}
            'k:{"port":1433,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:io.kompose.service': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  ports:
    - name: '1433'
      protocol: TCP
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: sql1
  clusterIP: 10.109.27.77
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
